definitions:
  majorcommands.CreateMajorCmdDTO:
    properties:
      name:
        type: string
    type: object
  nursecommands.CreateNurseAccountCmdDTO:
    properties:
      address:
        type: string
      certificate:
        type: string
      citizen-id:
        type: string
      city:
        type: string
      current-work-place:
        type: string
      district:
        type: string
      dob:
        type: string
      education-level:
        type: string
      email:
        type: string
      experience:
        type: string
      full-name:
        type: string
      gender:
        type: boolean
      google-drive-url:
        type: string
      major-id:
        type: string
      nurse-picture:
        type: string
      password:
        type: string
      phone-number:
        type: string
      slogan:
        type: string
      ward:
        type: string
    type: object
info:
  contact: {}
  description: |-
    Auth-service: https://api.curanest.com.vn/auth/swagger/index.html.
    Patient-service: https://api.curanest.com.vn/patient/swagger/index.html.
    Nurse-service: https://api.curanest.com.vn/nurse/swagger/index.html.
    Appointment-service (not ready - expected): https://api.curanest.com.vn/appointment/swagger/index.html.
    Notification-service (not ready - expected): https://api.curanest.com.vn/notification/swagger/index.html.
  title: Nurse Service
  version: "1.0"
paths:
  /api/v1/majors:
    get:
      consumes:
      - application/json
      description: get major
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      summary: get major
      tags:
      - major
    post:
      consumes:
      - application/json
      description: create new major
      parameters:
      - description: account creation data
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/majorcommands.CreateMajorCmdDTO'
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: create new major - admin
      tags:
      - major
  /api/v1/nurses:
    post:
      consumes:
      - application/json
      description: create nurse account
      parameters:
      - description: account creation data
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/nursecommands.CreateNurseAccountCmdDTO'
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: create nurse account
      tags:
      - nurse
  /api/v1/nurses/{nurse-id}/staff:
    patch:
      consumes:
      - application/json
      description: update nurse to staff of major
      parameters:
      - description: Account ID (UUID)
        in: path
        name: nurse-id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: update nurse to staff of major
      tags:
      - nurse
  /api/v1/nurses/me:
    get:
      consumes:
      - application/json
      description: get nurse profile (me)
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: get nurse profile (me)
      tags:
      - nurse
  /ping:
    get:
      consumes:
      - application/json
      description: ping server
      produces:
      - application/json
      responses:
        "200":
          description: message success
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      summary: ping server
      tags:
      - ping
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
