definitions:
  majorcommands.CreateMajorCmdDTO:
    properties:
      name:
        type: string
    type: object
info:
  contact: {}
  description: |-
    Auth-service: https://api.curanest.com.vn/auth/swagger/index.html.
    Patient-service: https://api.curanest.com.vn/patient/swagger/index.html.
    Nurse-service: https://api.curanest.com.vn/nurse/swagger/index.html.
    Appointment-service (not ready - expected): https://api.curanest.com.vn/appointment/swagger/index.html.
    Notification-service (not ready - expected): https://api.curanest.com.vn/notification/swagger/index.html.
  title: Nurse Service
  version: "1.0"
paths:
  /api/v1/majors:
    get:
      consumes:
      - application/json
      description: get major
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      summary: get major
      tags:
      - major
    post:
      consumes:
      - application/json
      description: create new major
      parameters:
      - description: account creation data
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/majorcommands.CreateMajorCmdDTO'
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: create new major - admin
      tags:
      - major
  /ping:
    get:
      consumes:
      - application/json
      description: ping server
      produces:
      - application/json
      responses:
        "200":
          description: message success
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      summary: ping server
      tags:
      - ping
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
