definitions:
  nursecommands.CreateNurseAccountCmdDTO:
    properties:
      address:
        type: string
      certificate:
        type: string
      citizen-id:
        type: string
      city:
        type: string
      current-work-place:
        type: string
      district:
        type: string
      dob:
        type: string
      education-level:
        type: string
      email:
        type: string
      experience:
        type: string
      full-name:
        type: string
      gender:
        type: boolean
      google-drive-url:
        type: string
      nurse-picture:
        type: string
      password:
        type: string
      phone-number:
        type: string
      slogan:
        type: string
      ward:
        type: string
    type: object
  nursecommands.MapNursingServiceDTO:
    properties:
      service-ids:
        items:
          type: string
        type: array
    type: object
  nursequeries.StaffIdsQueryDTO:
    properties:
      ids:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
  description: |-
    Auth-service: https://api.curanest.com.vn/auth/swagger/index.html.
    Patient-service: https://api.curanest.com.vn/patient/swagger/index.html.
    Nurse-service: https://api.curanest.com.vn/nurse/swagger/index.html.
    Appointment-service (not ready - expected): https://api.curanest.com.vn/appointment/swagger/index.html.
    Notification-service (not ready - expected): https://api.curanest.com.vn/notification/swagger/index.html.
  title: Nurse Service
  version: "1.0"
paths:
  /api/v1/nurses:
    get:
      consumes:
      - application/json
      description: get nursing with filter
      parameters:
      - description: services id
        in: query
        name: service-id
        type: string
      - description: nursing name
        in: query
        name: nurse-name
        type: string
      - description: rate
        in: query
        name: rate
        type: string
      - description: page
        in: query
        name: page
        type: string
      - description: size
        in: query
        name: size
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: get nursing with filter
      tags:
      - nurse
    post:
      consumes:
      - application/json
      description: create nurse account
      parameters:
      - description: account creation data
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/nursecommands.CreateNurseAccountCmdDTO'
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: create nurse account
      tags:
      - nurse
  /api/v1/nurses/{nurse-id}:
    get:
      consumes:
      - application/json
      description: get detail of nursing
      parameters:
      - description: Nursing ID (UUID)
        in: path
        name: nurse-id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      summary: get detail of nursing
      tags:
      - nurse
  /api/v1/nurses/{nurse-id}/private-detail:
    get:
      consumes:
      - application/json
      description: get private detail of nursing
      parameters:
      - description: Nursing ID (UUID)
        in: path
        name: nurse-id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: get private detail of nursing
      tags:
      - nurse
  /api/v1/nurses/{nurse-id}/services:
    get:
      consumes:
      - application/json
      description: get service of nursing
      parameters:
      - description: Nursing ID (UUID)
        in: path
        name: nurse-id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: get service of nursing
      tags:
      - nurse
    post:
      consumes:
      - application/json
      description: map service with nursing
      parameters:
      - description: Nursing ID (UUID)
        in: path
        name: nurse-id
        required: true
        type: string
      - description: account creation data
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/nursecommands.MapNursingServiceDTO'
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: map service with nursing
      tags:
      - nurse
  /api/v1/nurses/me:
    get:
      consumes:
      - application/json
      description: get nurse profile (me)
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: get nurse profile (me)
      tags:
      - nurse
  /external/rpc/nurses/by-ids:
    post:
      consumes:
      - application/json
      description: get staff info by ids
      parameters:
      - description: account creation data
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/nursequeries.StaffIdsQueryDTO'
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: get staff info by ids
      tags:
      - 'rpc: nurse'
  /external/rpc/nurses/service/{service-id}:
    get:
      consumes:
      - application/json
      description: get staff info by ids
      parameters:
      - description: service ID (UUID)
        in: path
        name: service-id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: data
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: get staff info by ids
      tags:
      - 'rpc: nurse'
  /ping:
    get:
      consumes:
      - application/json
      description: ping server
      produces:
      - application/json
      responses:
        "200":
          description: message success
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request error
          schema: {}
      summary: ping server
      tags:
      - ping
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
